version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crypto-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1grs7fccrj8f0"
s3_prefix = "crypto-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
