AWSTemplateFormatVersion: '2010-09-09'
Description: KMS Key for us-west-2
Resources:
  WestKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
        - Sid: Enable Account Use
          Effect: Allow
          Principal:
            AWS:
              Fn::Join:
              - ''
              - - 'arn:aws:iam::'
                - Ref: AWS::AccountId
                - :root
          Action: kms:*
          Resource: '*'
Outputs:
  WestKey:
    Description: "ARN for Crypto API Key West"
    Value: !GetAtt WestKey.Arn